name: Update copyright year(s) in license file

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 1 *" # 03:00 AM on January 1

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            README.md
            LICENSE

  source:
    needs: readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commitTitle: Copyright year update
          prTitle: Copyright year update
          path: "*.py"

      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --squash --delete-branch
